### ISSUE TITLE
`go get` is broken since cdd605f5e2f5158c8d3f8f752cba0a53b0aac4ec

### ISSUE THREAD

**Issue by tamird** [google/netstack#18]
```shell
$ go get -u github.com/google/netstack/...
# github.com/google/netstack/tcpip/transport/ping
../go/src/github.com/google/netstack/tcpip/transport/ping/ping_packet_list.go:16:48: undefined: pingPacket
../go/src/github.com/google/netstack/tcpip/transport/ping/ping_packet_list.go:30:8: undefined: pingPacket
../go/src/github.com/google/netstack/tcpip/transport/ping/ping_packet_list.go:31:8: undefined: pingPacket
# github.com/google/netstack/tcpip/transport/icmp
../go/src/github.com/google/netstack/tcpip/transport/icmp/endpoint.go:31:2: undefined: icmpPacketEntry
```

This was broken in https://github.com/google/netstack/commit/cdd605f5e2f5158c8d3f8f752cba0a53b0aac4ec (https://github.com/google/gvisor/commit/b75aa515044367094e762985a4b1a1f0580e3ad6) which changed the names of generated files and the type definitions they contain.

@kevinGC @iangudger @amscanne

**Comment by tamird** [comment]
Fixed since https://github.com/google/netstack/commit/636916365c65986a3c56c8b1bc36314cfee82f40.
